# Generated by Django 4.2.4 on 2023-08-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='media/service_request/'),
        ),
    ]
